name: Build Packages
  
on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  build:
    name: Build Packages
    strategy:
      matrix:
        os: ["fedora:39", "fedora:40"]

    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Build Dependencies
      run: |      
        dnf install -y \
          dnf-plugins-core \
          fedora-packager \
          rpmdevtools \
          gcc
        dnf builddep -y freerdp.spec
        
        rpmdev-setuptree
        spectool -g -R freerdp.spec        
          
    - name: Build & package
      id: version
      run: |        
        release=$(echo "${{ matrix.os }}" | cut -d ":" -f 2)
        echo "::set-output name=release::$release"
        
        rpmbuild -ba freerdp.spec
        
    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: freerdp-f${{ steps.version.outputs.release }}
        path: |
          ~/rpmbuild/RPMS/**/*.rpm
