name: Build Packages
  
on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  build:
    name: Build Packages
    strategy:
      matrix:
        os: ["fedora:39", "fedora:40"]

    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Build Dependencies
      run: |      
        dnf install -y \
          dbus-glib-devel \
          rpm-build \
          ninja-build \
          cups-devel \
          systemd-devel \
          libuuid-devel \
          pulseaudio-libs-devel \
          gcc-c++ libXrandr-devel \
          gsm-devel \
          gcc \
          cmake \
          ccache \
          clang \
          git-clang-format \
          pam-devel \
          fuse3-devel \
          ffmpeg-free-devel \
          opus-devel \
          lame-devel \
          ocl-icd-devel \
          docbook-style-xsl \
          openssl-devel \
          libasan \
          libX11-devel \
          libXext-devel \
          libXinerama-devel \
          libXcursor-devel \
          libXi-devel \
          libXdamage-devel \
          libXv-devel \
          libxkbfile-devel \
          alsa-lib-devel \
          openh264-devel \
          libavcodec-free-devel \
          libavformat-free-devel \
          libavutil-free-devel \
          libswresample-free-devel \
          libswscale-free-devel \
          libusb1-devel \
          uriparser-devel \
          uuid-devel \
          SDL2-devel \
          SDL2_image-devel \
          SDL2_ttf-devel \
          pkcs11-helper-devel \
          pcsc-lite-devel \
          webkit2gtk4.0-devel \
          krb5-devel \
          cjson-devel \
          cairo-devel \
          soxr-devel \
          wayland-devel \
          wayland-protocols-devel
          
    - name: Build & package
      run: |
        rpmbuild -ba freerdp.spec

    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-freedrp
        path: |
          **/*.rpm
