name: Build Packages

env:
  FREERDP: "3.4.0"
  
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight UTC

jobs:
  build:
    name: Build Packages
    strategy:
      matrix:
        os: ["fedora:39", "fedora:40"]

    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Build Dependencies
      run: |      
        dnf install -y \
          dbus-glib-devel \
          rpm-build \
          ninja-build \
          cups-devel \
          systemd-devel \
          libuuid-devel \
          pulseaudio-libs-devel \
          gcc-c++ libXrandr-devel \
          gsm-devel \
          gcc \
          cmake \
          ccache \
          clang \
          git-clang-format \
          pam-devel \
          fuse3-devel \
          ffmpeg-free-devel \
          opus-devel \
          lame-devel \
          ocl-icd-devel \
          docbook-style-xsl \
          openssl-devel \
          libasan \
          libX11-devel \
          libXext-devel \
          libXinerama-devel \
          libXcursor-devel \
          libXi-devel \
          libXdamage-devel \
          libXv-devel \
          libxkbfile-devel \
          alsa-lib-devel \
          openh264-devel \
          libavcodec-free-devel \
          libavformat-free-devel \
          libavutil-free-devel \
          libswresample-free-devel \
          libswscale-free-devel \
          libusb1-devel \
          uriparser-devel \
          uuid-devel \
          SDL2-devel \
          SDL2_image-devel \
          SDL2_ttf-devel \
          pkcs11-helper-devel \
          pcsc-lite-devel \
          webkit2gtk4.0-devel \
          krb5-devel \
          cjson-devel \
          cairo-devel \
          soxr-devel \
          wayland-devel \
          wayland-protocols-devel \
          wget

    - name: Clone FreeRDP Repository
      run: git clone --depth 1 https://github.com/freerdp/freerdp.git

    - name: Build & package
      run: |
        cd freerdp/packaging/rpm
        sh ../scripts/*rpm*.sh
        wget https://pub.freerdp.com/releases/freerdp-$FREERDP.tar.bz2
        sed -i '/^Version:/ s/.*/Version:   $FREERDP/' freerdp-nightly.spec
        rpmbuild -ba freerdp-nightly.spec

    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-freedrp
        path: |
          **/*.rpm
