name: Build Packages
  
on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  build:
    name: Build Packages
    strategy:
      matrix:
        os: ["fedora:39", "fedora:40"]

    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Build Dependencies
      run: |      
        dnf install -y \
          dnf-plugins-core \
          fedora-packager \
          rpmdevtools \
          gcc
          
        dnf builddep -y freerdp.spec
          
    - name: Build & package
      run: |        
        rpmbuild -ba freerdp.spec

    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-freedrp
        path: |
          ~/rpmbuild/RPMS/**/*.rpm
