name: Build Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight UTC

jobs:
  build:
    name: Build Packages
    strategy:
      matrix:
        os: ["ubuntu", "fedora:39", "fedora:40"]

    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Build Dependencies
      run: |
        # Set timezone to skip configuring in apt
        export TZ=Europe/Warsaw
        ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
      
        if [ "${{ matrix.os }}" != "ubuntu" ]; then
          dnf config-manager --enable fedora-cisco-openh264
          dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
          dnf -y install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
          dnf install -y --allowerasing \
            dbus-glib-devel \
            rpm-build \
            ninja-build \
            cups-devel \
            systemd-devel \
            libuuid-devel \
            pulseaudio-libs-devel \
            gcc-c++ libXrandr-devel \
            gsm-devel \
            gcc \
            cmake \
            ccache \
            clang \
            git-clang-format \
            pam-devel \
            fuse3-devel \
            ffmpeg-devel \
            opus-devel \
            lame-devel \
            ocl-icd-devel \
            docbook-style-xsl \
            openssl-devel \
            libasan \
            libX11-devel \
            libXext-devel \
            libXinerama-devel \
            libXcursor-devel \
            libXi-devel \
            libXdamage-devel \
            libXv-devel \
            libxkbfile-devel \
            alsa-lib-devel \
            openh264-devel \
            libavcodec-free-devel \
            libavformat-free-devel \
            libavutil-free-devel \
            libswresample-free-devel \
            libswscale-free-devel \
            libusb1-devel \
            uriparser-devel \
            uuid-devel \
            SDL2-devel \
            SDL2_image-devel \
            SDL2_ttf-devel \
            pkcs11-helper-devel \
            pcsc-lite-devel \
            webkit2gtk4.0-devel \
            krb5-devel \
            cjson-devel \
            cairo-devel \
            soxr-devel \
            wayland-devel \
            wayland-protocols-devel
        else
          apt update
          apt install -y \
            ninja-build \
            build-essential \
            git-core \
            debhelper \
            cdbs \
            dpkg-dev \
            cmake \
            cmake-curses-gui \
            clang-format \
            ccache \
            opencl-c-headers \
            ocl-icd-opencl-dev \
            libmp3lame-dev \
            libopus-dev \
            libsoxr-dev \
            libpam0g-dev \
            pkg-config \
            xmlto \
            libssl-dev \
            docbook-xsl \
            xsltproc \
            libxkbfile-dev \
            libx11-dev \
            libwayland-dev \
            libxrandr-dev \
            libxi-dev \
            libxrender-dev \
            libxext-dev \
            libxinerama-dev \
            libxfixes-dev \
            libxcursor-dev \
            libxv-dev \
            libxdamage-dev \
            libxtst-dev \
            libcups2-dev \
            libpcsclite-dev \
            libasound2-dev \
            libpulse-dev \
            libgsm1-dev \
            libusb-1.0-0-dev \
            uuid-dev \
            libxml2-dev \
            libfaad-dev \
            libfaac-dev \
            libsdl2-dev \
            libsdl2-ttf-dev \
            libcjson-dev \
            libpkcs11-helper-dev \
            liburiparser-dev \
            libkrb5-dev \
            libsystemd-dev \
            libfuse3-dev \
            libswscale-dev \
            libcairo2-dev \
            libavutil-dev \
            libavcodec-dev \
            libswresample-dev \
            libwebkit2gtk-4.0-dev \
            libpkcs11-helper1-dev
        fi

    - name: Clone FreeRDP Repository
      run: git clone --depth 1 https://github.com/freerdp/freerdp.git

    - name: Package
      run: |
        if [ "${{ matrix.os }}" != "ubuntu" ]; then
          cd freerdp/packaging/rpm
          rpmbuild -ba freerdp-nightly.spec
        else
          cd freerdp/packaging/deb
          dpkg-buildpackage -us -uc -b
        fi

    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-freedrp
        path: |
          **/*.deb
          **/*.rpm
